
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvwnwqdpsnyhjutcbzyx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2d253cWRwc255aGp1dGNienl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNTUwNzYsImV4cCI6MjA1OTgzMTA3Nn0.E3HQATbNw1iDJTJGmBnLJqM8yc9t09ggBx9mosSeeh8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      storage: localStorage,
      detectSessionInUrl: true,
      flowType: 'pkce'
    },
    global: {
      fetch: (url, options = {}) => {
        return fetch(url, {
          ...options,
          signal: AbortSignal.timeout(15000), // Increased from 8 seconds to 15 seconds
        });
      },
    },
    db: {
      schema: 'public'
    },
    realtime: {
      timeout: 10000, // Increased from 5 seconds
      heartbeatIntervalMs: 30000,
    }
  }
);
