
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvwnwqdpsnyhjutcbzyx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2d253cWRwc255aGp1dGNienl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNTUwNzYsImV4cCI6MjA1OTgzMTA3Nn0.E3HQATbNw1iDJTJGmBnLJqM8yc9t09ggBx9mosSeeh8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      storage: localStorage
    },
    global: {
      // Add request handlers
      fetch: (url, options) => {
        // Configuring reasonable request timeouts
        return fetch(url, {
          ...options,
          // 30 second timeout for requests
          signal: options?.signal || AbortSignal.timeout(30000)
        });
      }
    },
    db: {
      // Connection pooling settings
      schema: 'public'
    },
    realtime: {
      // Improve realtime connections
      timeout: 30000
    },
    // Configure retries for reliability
    maxRetryCount: 3,
    retryDelay: 1000 // Start with 1 second retry delay
  }
);
